### ISSUE TITLE
Huge error - Don't know how to fix

### ISSUE THREAD

**Issue by PuttyDev** [iisp33dii/si0n-Source#11]
Getting this error after building and launching the cheat. Don't know how to fix.

`Unhandled Exception: System.InvalidCastException: Conversion from string "" to type 'Double' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Operators.AddObject(Object Left, Object Right)
   at bl4tant.cBasePlayer.Health() in C:\Users\Chris\Desktop\legit\Blatant\si0n Recode\SDK\BasePlayer.vb:line 19
   at bl4tant.cESP.GlowESPplayersonly(Boolean Esp, Boolean ModelColor) in C:\Users\Chris\Desktop\legit\Blatant\si0n Recode\Features\ESP.vb:line 990
   at bl4tant.cESP.GlowESP(Boolean Esp, Boolean ModelColor, Int32 Mode) in C:\Users\Chris\Desktop\legit\Blatant\si0n Recode\Features\ESP.vb:line 45
   at bl4tant.Module1.loop_esp() in C:\Users\Chris\Desktop\legit\Blatant\si0n Recode\Module1.vb:line 127
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

**Comment by iisp33dii** [comment]
it literally tells you where the errors occure, if you still cant fix it. Try to delete your config and redownload the one from github
