### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Dr4inder** [iisp33dii/si0n-Source#14]
Getting IndexOutOfRangeException
BasePlayer.vb
Line 95-103
it causes the game to crash

**Comment by iisp33dii** [comment]
probably because it was outdated? Try again please

**Comment by Dr4inder** [comment]
no. I updated it for panorama by myself

**Comment by Camikaze13** [comment]
System.InvalidCastException
  HResult=0x80004002
  Message=Bringing the string "" to the "Double" type is invalid.
  Source=Microsoft.VisualBasic
  StackTrace:
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Operators.AddObject(Object Left, Object Right)
   at si0n.cBasePlayer.Health()
   at si0n.cESP.GlowESPplayersonly(Boolean Esp, Boolean ModelColor)
   at si0n.Module1.loop_esp()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Inner Exception 1:
FormatException: The input string was not in the correct format.
![image](https://user-images.githubusercontent.com/42093940/43713540-609c81ec-9993-11e8-8e6b-8574bd0bca40.png)

**Comment by Camikaze13** [comment]
How I can fix this?

**Comment by Kuhicop** [comment]
@Camikaze13 fixed¿? I have the same error

**Comment by ghost** [comment]
Same issue. no luck, It must be the game or something.

**Comment by iisp33dii** [comment]
I just updated the cheat, try if it works now
